config/routes.rb
Feedonme::Application.routes.draw do
  resources :read_entries

  resources :unread_entries

  resources :feeds
  resources :subscriptions
  
  get "feeds/:id/entries" => "entries#index", as: "show_feed_entries"
  get "feeds/:id/unread_entries" => "unread_entries#index", as: "show_feed_unread_entries"
  get "entries/:id/" => "entries#show", as: "show_feed_entry"
  
  post "entries/:id/mark_as_read" => "unread_entries#delete", as: "mark_entry_as_read"

  get "home/index"
  root to: "home#index"

  devise_for :users

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed
	has_many :unread_entries
	has_many :read_entries
	
	
	def self.fetch_feed_entries
		feeds=Feed.all
		feeds.each do |feed|
			current_feed=Feed.find(feed.id)
			feedzirra = Feedzirra::Feed.fetch_and_parse(feed.feedurl)
			feedzirra.entries.each do |entry|
				if entry.title.nil?
				else
					unique_entriy_hash=Digest::MD5.hexdigest(entry.title+feed.id.to_s)
					
					if entry.published.nil?
						entry_date=Time.now.to_datetime
					else
						entry_date=entry.published
					end
				
					if entry.content
						current_feed.entries<<Entry.find_or_create_by_unique_entriy_hash(unique_entriy_hash,title: entry.title, content: entry.content, unique_entriy_hash: unique_entriy_hash, date: entry_date, url: entry.url)
					elsif entry.summary
						current_feed.entries<<Entry.find_or_create_by_unique_entriy_hash(unique_entriy_hash,title: entry.title, content: entry.summary, unique_entriy_hash: unique_entriy_hash, date: entry_date, url: entry.url)
					else
						current_feed.entries<<Entry.find_or_create_by_unique_entriy_hash(unique_entriy_hash,title: entry.title, content: "No content", unique_entriy_hash: unique_entriy_hash, date: entry_date, url: entry.url)
					end
				end
			end		
		end		
	end
	
	
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_filter :authenticate_user!
	def index		
		@entries=Feed.find(params[:id]).entries
		respond_to do |format|
			format.js
		end	
	end
	
	def show
		@entry=Entry.find(params[:id])
		@feedname=Feed.where("id=?",@entry.feed_id).first.name
		respond_to do |format|
			format.js
			format.html
		end	
	
	end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/show.html.erb
<%=raw @entry.content%>
<%= @entry.date%>
<%= link_to "Mark as Read", mark_entry_as_read_path(@entry.id), method: :delete, remote: true%>

app/views/entries/show.js.erb
$('#dashboard_entry').text("");
$('#dashboard_entry').append($('<div>').attr('id','entry_detail_<%=@entry.id%>').attr('class','entry_details'));
$('#entry_detail_<%=@entry.id%>').append("<h1 class='entry_detail_header'><a href='<%=@entry.url%>' target='_blank'><%=j raw @entry.title%></a></h1>");
$('#entry_detail_<%=@entry.id%>').append("<hr>");
$('#entry_detail_<%=@entry.id%>').append("<p class='entry_detail_date'><%=j raw @entry.date%></p>");
$('#entry_detail_<%=@entry.id%>').append("<p class='entry_detail_name'><%=j raw @feedname%></p>");
$('#entry_detail_<%=@entry.id%>').append("<hr>");
$('#entry_detail_<%=@entry.id%>').append("<div class='entry_detail_text'><%=j raw @entry.content%></div>");

$.ajax({
      type: "post",
      url: "/entries/<%= @entry.id %>/mark_as_read"
});