config/routes.rb
Feedonme::Application.routes.draw do
  resources :read_entries

  resources :unread_entries

  resources :feeds
  resources :subscriptions
  
  get "feeds/:id/entries" => "entries#index", as: "show_feed_entries"
  get "feeds/:id/unread_entries" => "unread_entries#index", as: "show_feed_unread_entries"
  get "entries/:id/" => "entries#show", as: "show_feed_entry"
  
  post "entries/:id/mark_as_read" => "unread_entries#delete", as: "mark_entry_as_read"

  get "home/index"
  root to: "home#index"

  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
	  	@current_user=current_user
	  	@user_subscription_all_unread_count=0
	  	@user_subscriptions=SubscriptionsController.list(@current_user)
	  	
	  	@user_subscriptions.each do |subscription|
	  		@user_subscription_all_unread_count+=subscription[:unread]
	  	end
	  	
	  else
	  	render "not_signed_in"
	  end
  end
  
  def not_signed_in
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%#<p>Your are logged in! <%=@current_user.email%></p>
<%#<%= link_to "Logout", destroy_user_session_path, method: :delete%>

<div id="dashboard_wrapper">

	<div id="dashboard_top">
		
	</div>
	<div id="dashboard_action_notification" hidden="true"><p></p></div>
		
	<div id="dashborad_subscription_form">		
		<%=render "subscriptions/new" %>
		<div id="dashboard_action_spinner"></div>
	</div>
	
	<div id="dashborad_options">
		<%= link_to "Log out", destroy_session_path(:user), :method => :delete %>
	</div>
	
	<div id="dashboard_subscriptions">		
		<%=render "subscriptions/list", collection: @user_subscriptions%>
	</div>
	<div id="dashboard_entries">
		<ul id="dashboard_entries_list">
		</ul>
	</div>
	<div id="dashboard_entry">

	</div>
	<div id="multi_subscription_selection_dialog">
	</div>

</div>

app/views/home/not_signed_in.html.erb
<h1>This is the new feedonme in ror</h1>
<p>
	<%= link_to "Login", new_user_session_path, method: :get%>
</p>
<p>
	<%= link_to "Sign Up", new_user_registration_path, method: :get%>
</p>