config/routes.rb
Feedonme::Application.routes.draw do
  resources :read_entries

  resources :unread_entries

  resources :feeds
  resources :subscriptions
  
  get "feeds/:id/entries" => "entries#index", as: "show_feed_entries"
  get "feeds/:id/unread_entries" => "unread_entries#index", as: "show_feed_unread_entries"
  get "entries/:id/" => "entries#show", as: "show_feed_entry"
  
  post "entries/:id/mark_as_read" => "unread_entries#delete", as: "mark_entry_as_read"

  get "home/index"
  root to: "home#index"

  devise_for :users

end

app/models/unread_entry.rb
class UnreadEntry < ActiveRecord::Base
	belongs_to :user
	belongs_to :feed
	belongs_to :entry
	
	def self.create_unread_entries
	
		User.all.each do |user|
			user.subscriptions.each do |subscription|
				Entry.where("feed_id=?",subscription.feed_id).each do |entry|	
					if UnreadEntry.where("entry_id=? and feed_id=? and user_id=?",entry.id,subscription.feed_id,user.id).first
					else
						if ReadEntry.where("entry_id=? and user_id=?",entry.id,user.id).first
						else
							create(entry_id: entry.id, feed_id: subscription.feed_id, user_id: user.id, date: entry.date )
						end
					end
				end
			end
		end		
	end
	
end

app/controllers/unread_entries_controller.rb
class UnreadEntriesController < ApplicationController
	before_filter :authenticate_user!
	
	def index			
		@unread_entries=Array.new	
		
		if params[:id]=="all"		
			current_user.unread_entries.order("date").reverse_order.all.each do |unread_entry|
				@unread_entries<<Entry.find(unread_entry.entry_id)
			end
				
			respond_to do |format|
				format.js
			end	
		else
			
			current_user.unread_entries.where("feed_id=?",params[:id]).order("date").reverse_order.each do |unread_entry|
				@unread_entries<<Entry.find(unread_entry.entry_id)
			end		
			respond_to do |format|
				format.js
			end
				
		end
		
	end
	
	def delete
		@entry_id=params[:id]
		
		@feed_id=Entry.where("id=?",@entry_id).first.feed_id
				
		current_user.unread_entries.where("entry_id=?",params[:id]).first.delete
		ReadEntry.create(entry_id: params[:id], user_id: current_user)
		respond_to do |format|
			format.js
		end	
	
	
	end


end

app/helpers/unread_entries_helper.rb
module UnreadEntriesHelper
end

app/views/unread_entries/delete.js.erb
$('#entries_id_<%=@entry_id%>').removeClass('entry_unread');
$('#entries_id_<%=@entry_id%>').addClass('entry_read');
var current_read_count=parseInt($('#subscription_unread_count_id_<%=@feed_id%>').html());
var current_read_count_all=parseInt($('#subscription_unread_count_id_all').html());
$('#subscription_unread_count_id_<%=@feed_id%>').html(current_read_count-1);
$('#subscription_unread_count_id_all').html(current_read_count_all-1);

app/views/unread_entries/index.html.erb
<% @unread_entries.each do |unread_entry|%>
<%=unread_entry.title%>
<%end%>

app/views/unread_entries/index.js.erb
<%require 'sanitize'%>
$('#dashboard_entries_list').empty();
<% @unread_entries.each do |entry|%>
$('#dashboard_entries_list').append(
														$('<li>').attr('class','entry_unselected entry_unread').attr('id','entries_id_<%=entry.id%>').append('<h2 class=""><%= j link_to entry.title, show_feed_entry_path(entry.id), remote: true%></h2><p class=""><%=j link_to Sanitize.clean(entry.content).at(0..70)+"...",show_feed_entry_path(entry.id), remote: true %></p>'));
<%end%>



$('#dashboard_entry div').remove(); 