config/routes.rb
Feedonme::Application.routes.draw do
  resources :read_entries

  resources :unread_entries

  resources :feeds
  resources :subscriptions
  
  get "feeds/:id/entries" => "entries#index", as: "show_feed_entries"
  get "feeds/:id/unread_entries" => "unread_entries#index", as: "show_feed_unread_entries"
  get "entries/:id/" => "entries#show", as: "show_feed_entry"
  
  post "entries/:id/mark_as_read" => "unread_entries#delete", as: "mark_entry_as_read"

  get "home/index"
  root to: "home#index"

  devise_for :users

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :feed
	belongs_to :user
	
	def self.add(url,user)
	
		if url.instance_of?(Array)
			@subscription=Array.new
			url.each do |url|
				feed = Feedzirra::Feed.fetch_and_parse(url)
				if Feed.where("feedurl=?",url).exists?
					existing_feed= Feed.where("feedurl=?",url).first
					existing_feed.used_count+=1
					existing_feed.save
					existing_feed.subscriptions.create(user_id: user, unread_count: feed.entries.count)
					@subscription<<existing_feed
				else
					new_feed=Feed.create(name: feed.title, feedurl: url, used_count: 1)
					new_feed.subscriptions.create(user_id: user, unread_count: feed.entries.count)
					@subscription<<new_feed
				end
			end
		else
			feed = Feedzirra::Feed.fetch_and_parse(url)
			if Feed.where("feedurl=?",url).exists?
				existing_feed= Feed.where("feedurl=?",url).first
				existing_feed.used_count+=1
				existing_feed.save
				existing_feed.subscriptions.create(user_id: user, unread_count: feed.entries.count)
				@subscription=existing_feed
			else
				new_feed=Feed.create(name: feed.title, feedurl: url, used_count: 1, pageurl: feed.url)
				new_feed.subscriptions.create(user_id: user, unread_count: feed.entries.count)
				@subscription=new_feed
			end
		end
		
	@subscription	
	
	end
	
		
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_filter :authenticate_user!
	include FeedsHelper

	def new		  	
  	input_url=params[:url]
  	
  	if input_url.nil?
  		input_url=Array.new
  		input_url=params[:multi_url]
   	end
  
  	feed = Feedzirra::Feed.fetch_and_parse(input_url)
  	
		respond_to do |format|			
			if feed==0 or feed.nil?
				@feeds=discover_feeds(input_url)
				if @feeds.nil?	or @feeds.empty?		
					format.js {render 'no_subscriptions_found'}			
				else
					if @feeds.length==1
						@subscription=Subscription.add(@feeds.first[0],current_user.id)
						format.js 						
					else
						format.js {render 'list_of_discovered_subscriptions'}
					end
				end
			else
				@subscription=Subscription.add(input_url,current_user.id)
				format.js 	 
			end
		end 		
		
	end

	def self.list(user)
		@subscriptions=Array.new
	
		Subscription.where("user_id=?",user.id).each do |subscription|			
			#@subscriptions<<Feed.find(subscription.feed_id)#<< {unread: user.unread_entries.where("feed_id=?",subscription.feed_id).count}
			@subscriptions<<{feed_id: Feed.find(subscription.feed_id).id, name: Feed.find(subscription.feed_id).name, unread: user.unread_entries.where("feed_id=?",subscription.feed_id).count }
		end
		@subscriptions
	end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper


end

app/views/subscriptions/_list.html.erb
<ul id="dashboard_subscription_list">
<li id="feed_id_all_unread>" class="subscription_unselected"><%=link_to "all unread", show_feed_unread_entries_path("all"), method: :get, remote: true%><div class="unread_feed_count"><p id="subscription_unread_count_id_all"> <%=@user_subscription_all_unread_count%></p></div></li>
<% @user_subscriptions.each do |subscription|%>
	<li id="feed_id_<%=subscription[:feed_id]%>" class="subscription_unselected"><%= link_to subscription[:name], show_feed_unread_entries_path(subscription[:feed_id]), method: :get, remote: true%><div class="unread_feed_count"><p id="subscription_unread_count_id_<%=subscription[:feed_id]%>"> <%=subscription[:unread]%></p></div></li>
<%end%>
</ul>

app/views/subscriptions/_list_of_discovered_subscriptions.html.erb
<p>This website has multiple feed options. Select the feeds you’re interested in.</p>


<%= form_tag new_subscription_path, remote: true, method: :get, id: 'add_subscription_form_js' do%>
	<div id="choos_feed_list_container">
		<% @feeds.each do |feed|%>
			<label><%=	check_box_tag "multi_url[]", feed[0]%><%=feed[1]%></label>
			<br>
		<%end%>	
	</div>
	<%= submit_tag "Subscribe"	%>

	
<%end%>

app/views/subscriptions/_new.html.erb
<%= form_tag new_subscription_path, method: :get, remote: true do%>
	<%= text_field_tag :url,nil, placeholder: "ULR/Feed", size: 32,id: "add_subscription_input", autocomplete: "off"%>
	<%= submit_tag "Subscribe", id: "add_subscription_btn", id: "new_subscriptions_sumbit_btn"%>
<%end%>

app/views/subscriptions/list_of_discovered_subscriptions.js.erb
$(function() {
	$('#multi_subscription_selection_dialog').html("<%= j render "list_of_discovered_subscriptions" %>").dialog({
		height: 350,
		minWidth: 700,
		modal: true,
		show: {
			effect: "clip",
			duration: 500
		},

	});
	
$('#dashboard_action_notification').text("");
	
});

app/views/subscriptions/new.js.erb
<%if @subscription.instance_of?(Array)%>
	<% @subscription.each do |subscription|%>
		$('#dashboard_subscription_list').append('<li id="feed_id_<%=subscription.id%>"><%= link_to subscription.name, show_feed_unread_entries_path(subscription.id), method: :get, remote: true%></li>');
	<%end%>
	$(".ui-dialog-titlebar-close").trigger('click');
<%else%>
	$('#dashboard_subscription_list').append('<li id="feed_id_<%=@subscription.id%>"><%= link_to @subscription.name, show_feed_unread_entries_path(@subscription.id), method: :get, remote: true%></li>');
<%end%>
$('form :text').val("");
$('#add_subscription_btn').attr("disabled", false);

$("#dashboard_action_spinner").text("");
		$("#dashboard_action_notification").fadeIn();	
		$("#dashboard_action_notification p").text("Feed Added");
    setTimeout(function() {
    		$("#dashboard_action_notification").fadeOut();
        $("#dashboard_action_notification p").text("");
        $('#add_subscription_btn').attr("disabled", false);
}, 2000); 

app/views/subscriptions/no_subscriptions_found.js.erb
$(function() {
		$("#dashboard_action_spinner").text("");
		$("#dashboard_action_notification").fadeIn();	
		$("#dashboard_action_notification p").text("No Feed Found");
    setTimeout(function() {
    		$("#dashboard_action_notification").fadeOut();
        $("#dashboard_action_notification p").text("");
        $('#add_subscription_btn').attr("disabled", false);
    }, 2300);    
});